services:
  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - .docker:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=gatekeeper
      - POSTGRES_PASSWORD=gatekeeper
      - POSTGRES_DB=gatekeeper
    ports:
      - 5432:5432
